
### Проект

Ваша основная задача - выявить естественные жанры на основе индивидуальных музыкальных предпочтений и визуально представить результаты.

*Данные:* 
3 датасета на выбор в этой же папке. В каждом из них:
*Пользователи lastfm с характристиками:* пол, возраст, страна, дата регистрации
*История прослушиваний по пользователю:* время, id исполнителя, имя исполнителя, id трека, название трека

*Что сделать:* 
1) Выбрать один из трёх датасетов с пользователями и их музыкальными предпочтениями (в каждом ~330 пользователей)
2) Провести разведочный анализ данных (какие-то интересные закономерности, чтобы понять, что может влиять на предпочтения в прослушивании музыки) (и не забыть про препроцессинг текста)
3) Выявить естественные жанры на основе индивидуальных предпочтений (и содержательно их проинтерпретировать)
4) Проверить, зависят ли получившиеся жанры в зависимости от каких-то характеристик пользователей (как проверять - зависит от метода: вспомните анализ кластеров (в частности в сетях), либо СТМ)
4) Визуально представить результаты 

*Методы:*

Минимум 2 метода из пройденного в этом модуле:

1) Структурное тематическое моделирование можно использовать и в качестве метода кластеризации. За счет того, что он использует представление текста в качестве "мешка слов", то есть, не учитывая контекст, что позволяет выявить там "естественные жанры" из часто встречающихся рядом песен или исполнителей.

2) Сети пользователей/исполнителей/песен/слов (ассортативность, корреляции и т.д.)

3) Кластеризация на основе текста

4) Карты 

*Формальное*
1) проект выполнятеся индивидуально
2) срок выполнения: 24.12 23:59
3) формат сдачи: файл в формате .rmd через Share Report (инструкция с напоминанием в ~/minor3_2019/gists.pdf)
4) до 18.12 вам нужно заполнить промежуточный отчет в степике с описанием предварительных результатов 
