---
title: Network tests
output: html_document
editor_options: 
  chunk_output_type: console
---

Сегодня вспоминаем ВСЕ. Начнем с текстов, которые плавно перейдут в сети и, в итоге, в карты (сколько успеете).

Работаем с новостными статьями газеты Guardian. В датасете имеется:
*fields.bodyText* - текст статьи
*sectionName* - название секции, в которой была опубликована статья
*webPublicationDate* - дата публикации
*webTitle* - название статьи


1.Для начала оставьте только те статьи, в которых упоминаются следующие страны: Russia, Australia, China (hint: используйте str_detect для каждой страны). 

2. Посчитайте самые характерные слова (tf-idf) для каждой страны. Разнятся ли они?

3. Разбейте тексты на биграммы, постройте сеть корреляций. Примените алгоритм обнаружения сообществ и проинтерпретируйте кластеры.

4. Теперь отберите статьи, в которых помимо России, Австралии и Китая также упоминаются Chile, Syria, India, France, Belgium, Italy, Kazakhstan, Japan, Vietnam. 
  - Постройте бимодальную сеть, в которой будут статьи и страны. 
  - Сделайте проекцию стран, где толщина связи отражает количество упоминаний в одной статье. 
  
5. Замените страны на их столицы (из датасета *concap* в той же папке) и отрисуйте на карте новую сеть (связь между столицами, а не странами) 

```{r}
library(readr)
guardian = read_csv("./guardian.csv")
```

