---
title: 'SQL: HW'
output: html_document
---

## Задание на проект

Итак, ваша задача -- проанализировать данные ухода/оттока (на выбор даны две базы: одна про клиентов банка, вторая -- про сотрудников компании) и представить результаты в компактной и понятной форме.

Что нужно:

* исследуйте разные подгруппы клиентов/сотрудников. Выделите подгруппу, которая представляет наибольший интерес, обоснуйте свой выбор
* постройте модель для предсказания оттока (любым методом на ваш выбор)
* выявите основные факторы, которые значимы для предсказания оттока согласно этой модели
* предложите, какие действия могла бы предпринять компания, чтобы предотвратить/уменьшить отток. Обоснуйте свои предложения
* протестируйте с помощью предсказаний эффект от ваших предложений
* опишите ваши действия, их обоснования и результаты в отчете в формате Rmd
* проиллюстрируйте основной полученный результат с помощью дэшборда

Формальное:

* проект выполняется индивидуально
* это задание на работу с базой данных, вам нужно показать свое умение составлять запросы, вытаскивать в окружение R только часть данных, необходимую для анализа. За загрузку сразу всего датасета решения будут штрафоваться
* дэшборд -- это **краткое** представление результатов, страйтесь уместить результаты на одну страницу, не нужно переносить все этапы анализа в дэшборд, выберите интересное и необходимое.
* срок выполнения: 24.12 23:59
* формат сдачи: два файла (отчет и дэшборд) в формате .rmd через Share Report (инструкция с напоминанием в ~/minor3_2019/gists.pdf)
* до 17.12 вам нужно заполнить промежуточный отчет в степике с описанием предварительных результатов (в основном, этапа с разведочным анализом)

### Данные

У вас на выбор два набора данных -- про клиентов банка и про сотрудников некоторой компании. Выбирайте ту задачу, что вам более интересна: 

1) анализ того, почему клиенты банка не заключают новые договоры
2) анализ того, почему уходят сотрудники компании

##### Клиенты банка

Данные в папке project "~/shared/minor3_2019/1-SQL/project/BankChurn.db". Содержит две таблицы

* churn
   * CustomerId: id клиента
   * Surname: фамилия клиента
   * CreditScore: кредитный скоринг клиента
   * CountryId: id страны
   * Gender: пол клиента
   * Age: возраст клиента
   * Tenure: как долго клиент сотрудничает с банком (в месяцах)
   * Balance: текущий баланс клиента
   * NumOfProducts: количество продуктов, которыми пользуется клиент (кредитов, карт, счетов)
   * HasCrCard: есть ли кредитная карта
   * IsActiveMember: является ли клиент активным (часто совершает действия )
   * EstimatedSalary: заработная плата клиента
   * Exited: ушел ли клиент (1- ушел, 0 - остался)
* country
   * CountryId: id страны
   * Country: название страны

##### Сотрудники компании

Данные в папке project "~/shared/minor3_2019/1-SQL/project/EmployeeChurn.db"

* cities
   * cityID: id города
   * city: название города
* departments
   * departmentID: id департамента
   * department: название департамента
* info
   * employeeID: id сотрудника
   * birthdate_key: дата рождения
   * orighiredate_key: дата приема на работу
   * terminationdate_key: дата увольнения (1.1.1900 если работает в текущий момент)
   * age: возраст
   * length_of_service: стаж работы в годах
   * cityID: id города
   * departmentID: id департамента
   * job_title: должность
   * store_name: название магазина
   * gender: пол
   * termreason_desc: описание причины увольнения
   * termtype_desc: тип причины увольнения (добровольно, недобровольно, не применимо)
   * status_year: год записи (год сбора данных (2015) для текущих сотрудников, год увольнения для ушедших)
   * status: статус сотрудника (active -- является сотрудником в текущий момент, terminated -- уже не является сотрудником)
   * business_unit: подразделение (магазин или офис)